require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EventsController do
  def mock_event(stubs={})
    @mock_event ||= mock_model(Event, stubs).as_null_object
  end

  def mock_property(stubs={})
    @mock_property ||= mock_model(WebProperty, stubs).as_null_object
  end

  describe "with http basic" do
    before(:each) do
      configvars_auth
    end
    
    describe "GET index" do
      it "assigns all events as @events" do
        WebProperty.stub(:find).with("42") { mock_property }
        mock_property.stub(:events) { [mock_event] }
        get :index, :web_property_id => "42"
        assigns(:events).should eq([mock_event])
      end
    end
  
    describe "GET show" do
      it "assigns the requested event as @event" do
        Event.stub(:find).with("37") do
          mock_event(:web_property => mock_property)
        end
        get :show, :id => "37", :web_property_id => "42"
        assigns(:event).should be(mock_event)
      end
    end
  end

  describe "GET index" do
    it "fails without authorization" do
      get :show, :id => "37", :web_property_id => "42"
      response.status.should == 401
    end
  end

  describe "GET show" do
    it "fails without authorization" do
      get :show, :id => "37", :web_property_id => "42"
      response.status.should == 401
    end
  end

  describe "GET new.js" do
    it "renders the Pwnalytics main JS" do
      get :new, :format => 'js'
      response.body.should include('Pwnalytics.onLoad')
    end
    
    it "contains the correct event post backend URL" do
      get :new, :format => 'js'
      response.body.should include(create_event_path)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created event as @event" do
        Event.stub(:create_from_params).with({'controller' => 'events',
            'action' => 'create', 'these' => 'params'}, 'Rails Testing',
            '0.0.0.0') { mock_event(:save => true) }
        post :create, {'these' => 'params'}, :format => 'gif'
        assigns(:event).should be(mock_event)
      end

      it "renders the gif file" do
        Event.stub(:new) { mock_event(:save => true) }
        post :create, :event => {}
        response.body.should == PwnalyticsJS::PwnalyticsJS.gif_contents
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event as @event" do
        Event.stub(:create_from_params).with({'controller' => 'events',
            'action' => 'create', 'these' => 'params'}, 'Rails Testing',
            '0.0.0.0') { mock_event(:save => false) }
        post :create, {'these' => 'params'}, :format => 'gif'
        assigns(:event).should be(mock_event)
      end

      it "renders the gif file" do
        Event.stub(:create_from_params) { mock_event(:save => false) }
        post :create, :format => 'gif'
        response.body.should == PwnalyticsJS::PwnalyticsJS.gif_contents
      end
    end
  end
end
