require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EventsController do
  fixtures :events, :web_properties, :web_pages, :web_visitors

  def mock_event(stubs={})
    @mock_event ||= mock_model(Event, stubs).as_null_object
  end

  def mock_property(stubs={})
    @mock_property ||= mock_model(WebProperty, stubs).as_null_object
  end


  describe "with http basic" do
    before(:each) do
      configvars_auth
    end
    
    describe "GET index" do
      it "assigns all events as @events" do
        get :index, :web_property_id => web_properties(:js_test).to_param
        assigns(:events).should include(events(:test_load))
      end
    end

    describe "GET index" do
      it "uses names param in events DB query" do
        get :index, :web_property_id => web_properties(:js_test).to_param,
                    :names => [:page]
        assigns(:events).should eq([events(:test_load)])

        get :index, :web_property_id => web_properties(:js_test).to_param,
                    :names => [:page, :unload]
        assigns(:events).should eq([events(:test_load), events(:test_unload)])

        get :index, :web_property_id => web_properties(:js_test).to_param,
                    :names => []
        assigns(:events).should be_empty
      end
    end

    describe "GET show" do
      it "assigns the requested event as @event" do
        Event.stub(:find).with("37") do
          mock_event(:web_property => mock_property)
        end
        get :show, :id => "37", :web_property_id => "42"
        assigns(:event).should be(mock_event)
      end
    end
    
    describe "GET index via JSON" do
      it "renders events via to_api_hash" do
        WebProperty.stub(:find).with('42') { mock_property }
        mock_result = [mock_event]
        mock_property.stub(:events) { mock_result }
        mock_result.stub(:where) { mock_result }
        mock_result.stub(:includes) { mock_result }
        mock_event.stub(:to_api_hash) { { 'api' => 'hash' } }
        get :index, :web_property_id => '42', :format => 'json'
        ActiveSupport::JSON.decode(response.body).should == [{ 'api' => 'hash'}]
      end
    end

    describe "GET show via JSON" do
      it "renders requested event via to_api_hash" do
        Event.stub(:find).with('37') do
          mock_event(:web_property => mock_property)
        end
        mock_event.stub(:to_api_hash) { { 'api' => 'hash' } }
        get :show, :id => '37', :web_property_id => '42', :format => 'json'
        ActiveSupport::JSON.decode(response.body).should == { 'api' => 'hash'}
      end
    end
  end

  describe "GET index" do
    it "fails without authorization" do
      get :show, :id => "37", :web_property_id => "42"
      response.status.should == 401
    end
  end

  describe "GET show" do
    it "fails without authorization" do
      get :show, :id => "37", :web_property_id => "42"
      response.status.should == 401
    end
  end
end
