require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WebPagesController do
  def mock_web_page(stubs={})
    @mock_web_page ||= mock_model(WebPage, stubs).as_null_object
  end

  def mock_property(stubs={})
    @mock_property ||= mock_model(WebProperty, stubs).as_null_object
  end

  describe "with http basic" do
    before(:each) do
      configvars_auth
    end
    
    describe "GET index" do
      it "assigns all web_pages as @web_pages" do
        WebProperty.stub(:find).with("42") { mock_property }
        mock_property.stub(:web_pages) { [mock_web_page] }
        get :index, :web_property_id => "42"
        assigns(:web_pages).should eq([mock_web_page])
      end
    end
  
    describe "GET show" do
      it "assigns the requested web_page as @web_page" do
        WebPage.stub(:find).with("37") do
          mock_web_page(:web_property => mock_property)
        end
        get :show, :id => "37", :web_property_id => "42"
        assigns(:web_page).should be(mock_web_page)
      end
    end
  end

  describe "GET index" do
    it "fails without authorization" do
      get :index, :web_property_id => "42"
      response.status.should == 401
    end
  end

  describe "GET show" do
    it "fails without authorization" do
      get :show, :id => "37", :web_property_id => "42"
      response.status.should == 401
    end
  end
end
