require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WebVisitorsController do
  def mock_web_visitor(stubs={})
    @mock_web_visitor ||= mock_model(WebVisitor, stubs).as_null_object
  end


  describe "with http basic" do
    before(:each) do
      configvars_auth
    end

    describe "GET index" do
      it "assigns all web_visitors as @web_visitors" do
        WebVisitor.stub(:all) { [mock_web_visitor] }
        get :index
        assigns(:web_visitors).should eq([mock_web_visitor])
      end
    end
  
    describe "GET show" do
      it "assigns the requested web_visitor as @web_visitor" do
        WebVisitor.stub(:find).with("37") { mock_web_visitor }
        get :show, :id => "37"
        assigns(:web_visitor).should be(mock_web_visitor)
      end
    end
  end

  describe "GET index" do
    it "fails without authorization" do
      get :index
      response.status.should == 401
    end
  end

  describe "GET show" do
    it "fails without authorization" do
      get :show, :id => "37"
      response.status.should == 401
    end
  end  
end
