require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WebVisitorsController do

  def mock_web_visitor(stubs={})
    @mock_web_visitor ||= mock_model(WebVisitor, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all web_visitors as @web_visitors" do
      WebVisitor.stub(:all) { [mock_web_visitor] }
      get :index
      assigns(:web_visitors).should eq([mock_web_visitor])
    end
  end

  describe "GET show" do
    it "assigns the requested web_visitor as @web_visitor" do
      WebVisitor.stub(:find).with("37") { mock_web_visitor }
      get :show, :id => "37"
      assigns(:web_visitor).should be(mock_web_visitor)
    end
  end

  describe "GET new" do
    it "assigns a new web_visitor as @web_visitor" do
      WebVisitor.stub(:new) { mock_web_visitor }
      get :new
      assigns(:web_visitor).should be(mock_web_visitor)
    end
  end

  describe "GET edit" do
    it "assigns the requested web_visitor as @web_visitor" do
      WebVisitor.stub(:find).with("37") { mock_web_visitor }
      get :edit, :id => "37"
      assigns(:web_visitor).should be(mock_web_visitor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created web_visitor as @web_visitor" do
        WebVisitor.stub(:new).with({'these' => 'params'}) { mock_web_visitor(:save => true) }
        post :create, :web_visitor => {'these' => 'params'}
        assigns(:web_visitor).should be(mock_web_visitor)
      end

      it "redirects to the created web_visitor" do
        WebVisitor.stub(:new) { mock_web_visitor(:save => true) }
        post :create, :web_visitor => {}
        response.should redirect_to(web_visitor_url(mock_web_visitor))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved web_visitor as @web_visitor" do
        WebVisitor.stub(:new).with({'these' => 'params'}) { mock_web_visitor(:save => false) }
        post :create, :web_visitor => {'these' => 'params'}
        assigns(:web_visitor).should be(mock_web_visitor)
      end

      it "re-renders the 'new' template" do
        WebVisitor.stub(:new) { mock_web_visitor(:save => false) }
        post :create, :web_visitor => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested web_visitor" do
        WebVisitor.stub(:find).with("37") { mock_web_visitor }
        mock_web_visitor.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :web_visitor => {'these' => 'params'}
      end

      it "assigns the requested web_visitor as @web_visitor" do
        WebVisitor.stub(:find) { mock_web_visitor(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:web_visitor).should be(mock_web_visitor)
      end

      it "redirects to the web_visitor" do
        WebVisitor.stub(:find) { mock_web_visitor(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(web_visitor_url(mock_web_visitor))
      end
    end

    describe "with invalid params" do
      it "assigns the web_visitor as @web_visitor" do
        WebVisitor.stub(:find) { mock_web_visitor(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:web_visitor).should be(mock_web_visitor)
      end

      it "re-renders the 'edit' template" do
        WebVisitor.stub(:find) { mock_web_visitor(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested web_visitor" do
      WebVisitor.stub(:find).with("37") { mock_web_visitor }
      mock_web_visitor.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the web_visitors list" do
      WebVisitor.stub(:find) { mock_web_visitor }
      delete :destroy, :id => "1"
      response.should redirect_to(web_visitors_url)
    end
  end

end
