require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WebPagesController do

  def mock_web_page(stubs={})
    @mock_web_page ||= mock_model(WebPage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all web_pages as @web_pages" do
      WebPage.stub(:all) { [mock_web_page] }
      get :index
      assigns(:web_pages).should eq([mock_web_page])
    end
  end

  describe "GET show" do
    it "assigns the requested web_page as @web_page" do
      WebPage.stub(:find).with("37") { mock_web_page }
      get :show, :id => "37"
      assigns(:web_page).should be(mock_web_page)
    end
  end
end
