require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WebVisitorsController do
  def mock_web_visitor(stubs={})
    @mock_web_visitor ||= mock_model(WebVisitor, stubs).as_null_object
  end

  def mock_property(stubs={})
    @mock_property ||= mock_model(WebProperty, stubs).as_null_object
  end

  describe "with http basic" do
    before(:each) do
      configvars_auth
    end

    describe "GET index" do
      it "assigns all web_visitors as @web_visitors" do
        WebProperty.stub(:find).with("42") { mock_property }        
        mock_property.stub(:web_visitors)  { [mock_web_visitor] }
        get :index, :web_property_id => "42"
        assigns(:web_visitors).should eq([mock_web_visitor])
      end
    end
  
    describe "GET show" do
      it "assigns the requested web_visitor as @web_visitor" do
        WebVisitor.stub(:find).with("37") do
          mock_web_visitor(:web_property => mock_property)
        end
        get :show, :id => "37", :web_property_id => "42"
        assigns(:web_visitor).should be(mock_web_visitor)
      end
    end
    
    describe "GET index via JSON" do
      it "renders pages via to_api_hash" do
        WebProperty.stub(:find).with('42') { mock_property }
        mock_property.stub(:web_visitors) { [mock_web_visitor] }
        mock_web_visitor.stub(:to_api_hash) { { 'api' => 'hash' } }
        get :index, :web_property_id => '42', :format => 'json'
        ActiveSupport::JSON.decode(response.body).should == [{ 'api' => 'hash'}]
      end
    end

    describe "GET show via JSON" do
      it "renders requested event via to_api_hash" do
        WebVisitor.stub(:find).with('37') do
          mock_web_visitor(:web_property => mock_property)
        end
        mock_web_visitor.stub(:to_api_hash) { { 'api' => 'hash' } }
        get :show, :id => '37', :web_property_id => '42', :format => 'json'
        ActiveSupport::JSON.decode(response.body).should == { 'api' => 'hash'}
      end
    end
  end

  describe "GET index" do
    it "fails without authorization" do
      get :index, :web_property_id => "42"
      response.status.should == 401
    end
  end

  describe "GET show" do
    it "fails without authorization" do
      get :show, :id => "37", :web_property_id => "42"
      response.status.should == 401
    end
  end  
end
